% Circuits II Lab 2
% Black Box Circuit (SERIES RL)
% Due Date: 6/11/18
% Members: Noah Johanson, Josh Horejs, Sean Desautels

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Goals of the MATLAB code includes: 

%1. determine POWER GENERATED by source,
%2. POWER CONSUMED by the load (complex values)
%3. POWER FACTOR OF LOAD
%4. Collect data at 2 frequencies (1k and 2k Hz) and compare.  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear, clc;

% Require input for values needed to determine power. 

% Voltage of source

v_a_prompt = 'What is the source voltage? ';
v_a = input(v_a_prompt);

% Voltage of response

v_b_prompt = 'What is the response voltage? ';
v_b = input(v_b_prompt);

% Total resistance of the load

r_l_prompt = 'What is the load resistance? ';
r_l = input(r_l_prompt);

% What's the frequency, Kenneth?

freq_prompt = 'What is the frequency? ';
freq_1 = input(freq_prompt);

% Phase angle found at 1k Hz

phase_one_prompt = 'What is the phase shift between source and response voltage at 1k Hz? ';
phase_angle = input(phase_one_prompt);

%phase_angle_avg = (phase_angle_one + phase_angle_two) / 2; 

% The current running through the black box will be the same throughout the
% series. We can determine the current of the circuit by finding the
% current across the known resistance of the load resistance. 

i_r = (v_b) / (r_l);

i_eff = i_r / sqrt(2);

% We can determine impedance by using the found current with the source
% voltage and the resistance of the load. 

z_box = ((v_a) / (i_r)) - r_l ;

z_box_real = z_box * cosd(phase_angle); 

z_box_imag = z_box * (1j*sind(phase_angle));

z_box_complex = z_box_real + z_box_imag; 

z_total = r_l + z_box_complex ; 

% We can determine the inductor by dividing the impedance of the circuit by
% the frequency given. 

% inductor_val_one = ((z_box)*(sin(phase_angle))) / (2 * pi * freq_1);

% Commented out REAL inductor value

inductor_val_one = 0.010 ; 

inductor_val_real = abs(inductor_val_one) ;

capacitor_z = -(inductor_val_one);

capacitor_val = inductor_val_one/((z_box_real)^2 + ((2*pi*freq_1)^2)*((inductor_val_one)^2)) ; 

% capacitor_val_calc = (1j*(inductor_val_one - (z_box/freq_1) + (z_box/(freq_1*.97)))) / ((1/97)*(z_box*1j*freq_1*inductor_val_one)*(z_box_real*z_box)) ;


% Power Factor

pf = (r_l)/(z_box);

% Phase angle

angle = acosd(pf);

% Reactive Factor

rf = sind(angle);

% Average Power P 

P = (.5 * v_a * i_r) * cosd(phase_angle);

% Reactive Power Q

Q = (.5 * v_a * i_r) * sind(phase_angle);

% Apparent Power S

S = sqrt(P^2 + Q^2) ; 

% impedance of inductor

x_total = ((v_a)^2)/ Q;

% Total impedance 

Z = sqrt(((r_l)^2) + (((x_total)^2))) ;



% Print out found values

fprintf ('The Average Power is %e W . \n ' , P);
fprintf ('The Reactive Power is %e VAR . \n ' , Q);
fprintf ('The Apparent Power is %e VA . \n ', S);
fprintf ('The Power Factor is %1.2f . \n ' , pf);
fprintf ('The capacitor needed for optimal power is %e F . \n ' , capacitor_val);
